version: "3.7"
services:
  webapi:
    container_name: 'webapi'
    build:
      context: .
      dockerfile: ./conversion.api/dockerfile
    depends_on:
      - "db"
    networks:
      - my-network

  webapp:
    container_name: 'webapp'
    build:
      context: .
      dockerfile: ./conversion-website/dockerfile
    depends_on:
      - "db"
    networks:
      - my-network
      
  db:
    container_name: 'postgres'
    image: postgres
    networks:
     - my-network

networks:
  my-network:
    driver: bridge